#ifndef __BSP_EXTI_KEY_H
#define __BSP_EXTI_KEY_H

#include "stm32f10x.h"



#define KEY1_EXTI_GPIO_CLK			RCC_APB2Periph_GPIOA
#define KEY1_EXTI_GPIO_PORT			GPIOA
#define KEY1_EXTI_GPIO_PIN			GPIO_Pin_0
#define KEY1_EXTI_GPIO_PORTSOURCE GPIO_PortSourceGPIOA
#define KEY1_EXTI_GPIO_PinSOURCE  GPIO_PinSource0
#define KEY1_EXTI_LINE					EXTI_Line0
#define KEY1_EXTI_IRQN          EXTI0_IRQn
#define KEY1_EXTI_IRQHANDLER    EXTI0_IRQHandler


#define KEY2_EXTI_GPIO_CLK			RCC_APB2Periph_GPIOC
#define KEY2_EXTI_GPIO_PORT			GPIOC
#define KEY2_EXTI_GPIO_PIN			GPIO_Pin_13
#define KEY2_EXTI_GPIO_PORTSOURCE GPIO_PortSourceGPIOC
#define KEY2_EXTI_GPIO_PinSOURCE  GPIO_PinSource13
#define KEY2_EXTI_LINE					EXTI_Line13
#define KEY2_EXTI_IRQN          EXTI15_10_IRQn
#define KEY2_EXTI_IRQHANDLER    EXTI15_10_IRQHandler

void EXTI_KEY_Config(void);

#endif /*__BSP_EXTI_KEY_H*/
